name: Contracts Test (Solidity v0.6.0)
on: push

jobs:
  brownie:
    runs-on: ubuntu-latest

    steps:
    - name: Check out GitHub repository
      uses: actions/checkout@v2

    - name: Cache compiler installations
      uses: actions/cache@v2
      with:
        path: |
          ~/.solcx
          ~/.vvm
        key: ${{ runner.os }}-compiler-cache

    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install ganache-cli
      run: npm install -g ganache-cli@6.11

    - name: Set up python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set pip cache directory path
      id: pip-cache-dir-path
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
      working-directory: ./src/v0.6.0


    - name: Restore pip cache
      uses: actions/cache@v2
      id: pip-cache
      with:
        path: |
          ${{ steps.pip-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          ${{ runner.os }}-pip-

    - name: Install python dependencies
      run: pip install -r requirements-dev.txt
      working-directory: ./src/v0.6.0

    - name: Run tests
      run: brownie test tests/ -s --coverage
      working-directory: ./src/v0.6.0
